#!/bin/sh

WFOLDER=src 

# Filesystem watcher

if ! command -v fswatch > /dev/null; then 
  if $darwin; then
    if ! command -v brew > /dev/null; then 
      echo "Error: fswatch can not be installed in this platform due brew is not detected"
    else 
      echo "Installing fswatch using brew"
      brew install fswatch;
    fi
  else 
    echo "fswatch not detected"
    exit 1;
  fi
fi

echo "Starting watcher on $WFOLDER"
fswatch -d $WFOLDER | xargs -n1 -I{} $0 compile $(echo "$@" | sed 's/spring-boot:run//')
